version: '3'

services:
  db:
    image: isgenez/mysql57
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
    networks:
      - dbnet

  realworld-be:
    image: isgenez/backend
    depends_on:
      - db
    ports:
      - 8080:8080
    links:
      - db:mysql
    networks:
      - appnet
      - dbnet

  realworld-fe:
    image: isgenez/frontend
    depends_on:
      - realworld-be
    ports:
      - 3000:3000
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.1/16

  dbnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.1/16
