FROM openjdk:8-alpine

RUN apk add --no-cache maven alpine-sdk && \
    mkdir -p /usr/app

COPY target/api-0.0.1-SNAPSHOT.jar /usr/app/
WORKDIR /usr/app

CMD ["java", "-Djava.security.egd=file:/dev/./urandom", -"jar", "api-0.0.1-SNAPSHOT.jar"]

